title: Sunset Dimmer
logo: /assets/logo.png
description: Magic tool to save your eyes when working on computer at night.
show_downloads: false
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
